# Generated by Django 3.1.4 on 2021-04-26 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuoteApp', '0003_auto_20210426_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepost',
            name='likes',
        ),
        migrations.AddField(
            model_name='quotepost',
            name='likes',
            field=models.ManyToManyField(related_name='quote_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
