# Generated by Django 3.1.4 on 2021-04-26 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuoteApp', '0004_auto_20210426_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotepost',
            name='likes',
            field=models.ManyToManyField(related_name='quote_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
